version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: patient-service-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    platform: linux/amd64  # Specify the platform

  patient-service:
    image: bijaysedhain/patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    platform: linux/amd64  # Specify the platform