name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          cd patient-service
          mvn clean install

      - name: Run tests
        run: |
          cd patient-service
          mvn test

      - name: Package application
        run: |
          cd patient-service
          mvn package

      - name: Run SpotBugs
        run: |
          cd patient-service
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

      - name: Check DOCKER_USERNAME length
        run: |
          echo "DOCKER_USERNAME length: ${#DOCKER_USERNAME}"
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Check DOCKER_PASSWORD length
        run: |
          echo "DOCKER_PASSWORD length: ${#DOCKER_PASSWORD}"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          cd patient-service
          docker build -t patient-service:latest .

      - name: Push Docker image
        run: |
          docker tag patient-service:latest ${{ secrets.DOCKER_USERNAME }}/patient-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/patient-service:latest