name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          cd patient-service
          mvn clean install

      - name: Run tests
        run: |
          cd patient-service
          mvn test

      - name: Package application
        run: |
          cd patient-service
          mvn package

      - name: Run SpotBugs
        run: |
          cd patient-service
          mvn com.github.spotbugs:spotbugs-maven-plugin:spotbugs

#      - name: Log in to Docker Hub
#        run: echo "-e4s@4TB*U3j(Pu" | docker login -u "bijaysedhain" --password-stdin
#
#      - name: Build Docker image
#        run: |
#          cd patient-service
#          docker build -t patient-service:latest -f Dockerfile .
#
#      - name: Push Docker image
#        run: |
#          docker tag patient-service:latest bijaysedhain/patient-service:latest
#          docker push bijaysedhain/patient-service:latest